### ISSUE TITLE
Keinen eigenen Cache-Buster verwenden

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/newsmanager#1]
Die Einbindung der Assets mittels `?v=' . $this->getVersion())` ist nicht mehr empfohlen, weil REX 5.3 inzwischen einen eigenen Cache-Buster mitbringt.

Nutzer mit REX <5.3 müssten dann u. U. nach einem AddOn-Update ihren Browsercache löschen. Allerdings auch nur dann, wenn das AddOn neue Assets publiziert und wenn der Browser die Änderungen nicht sowieso schon eigenständig mitbekommt.

**Comment by georgkaser** [comment]
Danke für den Hinweis!
