### ISSUE TITLE
Whoops - Methoden fehlen

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/newsmanager#10]
Nimmt man den Code aus der Readme, dann erscheint ein Whoops `Call to undefined method NewsManager::getCommentList()`

```
echo $newsmanager->getCommentList($article_post->getPid());
echo $newsmanager->getCommentForm($article_post->getPid());
```

PlugIns sind bewusst nicht installiert.

**Comment by georgkaser** [comment]
Hast du die abgeleitete Klasse `NewsManagerWithComments()` verwendet? Weiß nicht ob man das so macht, wenn's da eine bessere Lösung gibt, gerne sagen.

**Comment by tbaddade** [comment]
Ich habe den Code aus der Readme einfach ins Template kopiert. Hab da nichts angepasst.

**Comment by georgkaser** [comment]
Ich hab im Plugin eine abgeleitete Klasse erstellt. Die muss verwendet werden. Muss ich vielleicht 2 Beispiele im Readme machen...

**Comment by skerbis** [comment]
Ich würde prüfen welche Plugins aktiv sind und dann den richtigen Aufruf starten. Dann muss niemand darüber nachdenken.

**Comment by georgkaser** [comment]
Hmm, interessante Idee - ich hab mal ein bisschen rumgespielt. In der Elternklasse hab ich jetzt folgende Funktion:
```php
    public static function create() {
        
        if (rex_addon::get('newsmanager')->getPlugin('comments')->isAvailable()) {
            $instance = new NewsManagerWithComments();
        } else {
            $instance = new self();
        }
        
        return $instance;
    }
```

Das Newsmanager Objekt wird dann über diese Funktion initialisiert:

```php
    $newsmanager = NewsManager::create();
```

Ob das guter Stil ist, weiß ich nicht. Aber ich muss da nicht mehr aufpassen. Verwende ich jedoch z.B. vorher das Plugin comments bzw. die Funktionen der abgeleiteten Klasse und deaktiviere es z. B. später - weil ich vielleicht keine Kommentare mehr nutzen möchte, plattelt es mich trotzdem auf. Aber das ist eh klar - oder? So idiotensicher muss das dann nicht sein, nicht? Was haltet ihr davon?

**Comment by skerbis** [comment]
Eine Alternative wäre mit namespaces zu arbeiten und der jewiligen Class den gewünschten alias geben

**Comment by georgkaser** [comment]
Mit Namespaces hab ich mich noch nicht beschäftigt (also nicht in PHP - in Java mit den Packages schon). Damit kann man ja die gleichen Klassennamen im jeweiligen Namespace verwenden - ich versteh aber nicht, wie mir das hier helfen kann? Kannst du mir ein kleines Beispiel geben?

**Comment by skerbis** [comment]
Ja und du kannst  switchen, du änderst entweder den namespace und rufst dann die andere class auf oder du rufst eine class als alias auf, so dass es der gleiche classaufruf bleibt.

**Comment by georgkaser** [comment]
Hmm, wenn ich aber das mit der Funktion mach wie [beschrieben](https://github.com/FriendsOfREDAXO/newsmanager/issues/10#issuecomment-338316654), dann muss ich nicht mal einen namespace ändern. Ist das nicht besser?
