### ISSUE TITLE
Erst das Objekt auf Null prüfen bevor Methode aufgerufen wird.

### ISSUE THREAD

**Issue by georgkaser** [FriendsOfREDAXO/newsmanager#13]
https://github.com/FriendsOfREDAXO/newsmanager/blob/dd1a80e403bd2fe0086342343910fb095ca13da4/lib/NewsManager.php#L245

**Comment by spiritandsoul** [comment]
Gibt es für den Bug schon eine Lösung? Würde dein cooles Addon gern nutzen wollen und weiß leider selbst nicht wie ich das lösen kann...

**Comment by georgkaser** [comment]
Nein, bin noch nicht dazu gekommen das zu beheben. Allerdings spielt das für die Verwendung keine Rolle, der Bug tritt nämlich nur auf, wenn du das Artikelobjekt nicht initialisiert hast. Das machst du so: `$article_post = $newsmanager->getArticleById($news_id);`
Lade dir am besten die letzte master Version hier herunter und verwende die so wie im Readme beschrieben - dann klappts auch ;)

**Comment by spiritandsoul** [comment]
Danke dir! Hatte ne Kleinigkeit beim kopieren übersehen... Jetzt läufts rund und bin begeistert vom Newsmanager!
