### ISSUE TITLE
Duplizieren eines Beitrags nicht möglich

### ISSUE THREAD

**Issue by claudihey** [FriendsOfREDAXO/newsmanager#14]
Bei Klick auf 'duplizieren' passiert nix... Schade, genau das hätte ich jetzt gut gebrauchen können... ;-)
Ansonsten aber ein sehr cooles Addon, Georg!

**Comment by georgkaser** [comment]
Kannst du dir mal die letzte Master Version installieren? Das hat sicher mit den URL Einstellungen (Sprache) zu tun, das hab ich schon gefixt.

**Comment by claudihey** [comment]
Supi, funktioniert! :D

**Comment by ansichtsache** [comment]
schade, was mache ich falsch? funtioniert bei mir leider nicht. welche zeile ist in der main.php jetzt richtig:
`if ($func == 'copy' && $pid > 0) {` 
oder
 `if ($func == 'copy' && $pid >= 0) {`

**Comment by claudihey** [comment]
Hast Du die letzte Master Version installiert? Ich denke mal, in der Version, die man über den Installer runterladen kann, ist der Fehler noch drin...

**Comment by ansichtsache** [comment]
habe mir die zip hier aus github geholt…

**Comment by claudihey** [comment]
Hmm, bei mir hat's mit der master dann funktioniert... Hier kann ich dann leider nicht weiterhelfen... 
@georgkaser ?

**Comment by ansichtsache** [comment]
hi @claudihey was steht denn in deiner main.php auf zeile 59?

**Comment by claudihey** [comment]
if ($func == 'copy' && $pid > 0) {

**Comment by georgkaser** [comment]
Gehts jetzt? Mit der letzten Github Master (nicht die Releases) sollte es jedenfalls problemlos funktionieren.

**Comment by ansichtsache** [comment]
habe mir die main.php nochmal  neu vom master gezogen – und siehe da: funzt…
warum die von gestern nicht ging – don't know.
danke euch beiden!
