### ISSUE TITLE
Individueller Metatitle

### ISSUE THREAD

**Issue by spiritandsoul** [FriendsOfREDAXO/newsmanager#15]
Gäbe es noch die Möglichkeit für eine individuelle Titelbeschreibung unter den SEO-Einstellungen? Manchmal möchte man noch die Überschrift des Artikel ansprechender machen ohne das sich gleich die URL ändert.

Danke für deine Arbeit, gelungendes Addon!

**Comment by georgkaser** [comment]
Im Moment noch nicht. Ich kann das aber einbauen, das ist kein Problem.

**Comment by webregie** [comment]
Das wäre hervorragend. Eine eigene URL erstellen.

**Comment by Markus-GS** [comment]
Moin!
Ist in Arbeit und wird "die Tage" released.

**Comment by Markus-GS** [comment]
Mit Release 1.2.3 implementiert.
