### ISSUE TITLE
Direktlink zum vorherigen und nächsten Beitrag

### ISSUE THREAD

**Issue by claudihey** [FriendsOfREDAXO/newsmanager#17]
Ich fänd es toll, wenn es in der Artikelansicht auch einen Direktlink zum vorherigen und zum nächsten Beitrag gäbe. Das erhöht die Benutzerfreundlichkeit für den Leser. Ansonsten wirklich ein tolles Addon, Georg! :-)

**Comment by eaCe** [comment]
@claudihey es gibt nun eine Funktion um die URL zu bekommen.

```php
$next = $article_post->getNextUrl();
$prev = $article_post->getPrevUrl();
```

null wenn nicht vorhanden, oder eben die URL zum Artikel
