### ISSUE TITLE
Dritter Status "Archiv"

### ISSUE THREAD

**Issue by ansichtsache** [FriendsOfREDAXO/newsmanager#18]
cool wäre ja ein dritter status "Archiv" – am besten mit "online von bis" – dann automatischer statuswechsel auf "Archiv". die so getaggten news könnten dann auf einer extraseite ausgegeben werden.

**Comment by georgkaser** [comment]
Kann man so machen, gute Idee. Umsetzung dauert noch, bin grad mit Arbeit zu ;)
