### ISSUE TITLE
unterminated entity reference

### ISSUE THREAD

**Issue by webregie** [FriendsOfREDAXO/newsmanager#24]
Ich habe eine Kategorie angelegt, wieder gelöscht und unter dem gleichen Namen wieder angelegt. Was bedeutet diese Fehlermeldung? Aktuelle 5.5.1.

Warning: DOMDocument::createElement() [domdocument.createelement]: unterminated entity reference Fotografie RSS Feed in /kunden//../redaxo/redaxo/src/addons/newsmanager/lib/NewsManager.php on line 397
Warning: DOMDocument::createElement() [domdocument.createelement]: unterminated entity reference Fotografie RSS Feed in /kunden//../redaxo/redaxo/src/addons/newsmanager/lib/NewsManager.php on line 400

**Comment by georgkaser** [comment]
Scheint als wäre da irgendwo ein < oder > Zeichen drin. Wie heißt denn die Kategorie? Hast du den Kategorienamen selbst eingetippt oder von irgendwoher reinkopiert?

**Comment by webregie** [comment]
Das ist ein guter Tipp. Aber selbst wenn ich die Kategorie lösche, habe ich noch immer diese Fehlermeldung. Nein, habe es selbst eingetippt. Könnte evtl. aus Windoof kommen, aber es sind keine Extrazeichen enthalten.

**Comment by webregie** [comment]
Die Kategorie hieß Fotografie. Ich habe sie gelöscht und Fotograf angelegt. Nun habe immer noch die gleiche Fehlermeldung darüber. Er meint immer Fotografie. Gibt es aber nicht mal mehr in der Datenbank.
