### ISSUE TITLE
In Single View Bild nach Text?

### ISSUE THREAD

**Issue by webregie** [FriendsOfREDAXO/newsmanager#25]
Ich habe noch keine Lösung gefunden. Im Teaser ist das Bild vor dem Text (richtext). In der Single View folgt das Bild aber auf den Text (oder mehrere Bilder). Wie kann ich das ändern? 
Durch die Logik des Aufbaus zu steigen ist nicht ganz easy... danke!

**Comment by georgkaser** [comment]
Ja, das stimmt. Die Darstellung der Ausgabe wird über die Views (data/views) geregelt. Leider hab ich das Bild da mit dem Richtext "vermantschkert" - heißt, das Bild wird nicht über eine Variable ausgegeben (warum weiß ich gar nicht mehr - eigentlich würde sich das anbieten). Ich werde das abändern. 
Abhelfen kannst du dir, indem du die Darstellung einfach über eine normale Datenbankabfrage machst und vorerst auf meine Funktion verzichtest.

**Comment by webregie** [comment]
Vielen Dank für die zeitnahe Antwort. Das ist natürlich ärgerlich. Ich möchte das ja gerne für weitere Websites einheitlich haben und auf die Funktion zurückgreifen. 
Es wäre wahrscheinlich sinnlos auf die gleiche Bilderdarstellung wie im Teaser zurückzugreifen, weil man ja vielleicht eine andere Ansicht in der Übersicht haben will (Blöcke). 
Wenn du einen Hinweis für die Herangehensweise hättest, würde ich mich freuen. Vielleicht kann man das ja schnell berichtigen. Denn du hast recht: In der Teaseransicht kann man per if image drauf zugreifen.

**Comment by georgkaser** [comment]
Schnell geht leider im Moment gar nichts :( Bin ziemlich mit Arbeit zu grad - aber ich geb mir Mühe das demnächst zu implementieren (es hat sich eh schon ein bisserl was angesammelt).

**Comment by webregie** [comment]
huhu! 
Wie ist denn der Stand? Können wir auf ein Update hoffen? Herr Ansichtssache hat ja einige Dinge eingebaut und die scheinen zu funktionieren... 

Gruß und Dank
Ralf

**Comment by eaCe** [comment]
In der aktuellen Github-Version werden Fragmente verwendet. Diese können, wie in der Dokumentation beschrieben, frei angepasst werden. https://www.redaxo.org/doku/main/fragmente
