### ISSUE TITLE
Single View bleibt leer…

### ISSUE THREAD

**Issue by ansichtsache** [FriendsOfREDAXO/newsmanager#26]
…wenn ich die `<hr />` für die trennung des teasers verwende.

kann es sein, dass in der NewsManagerArticle.php die public function "printArticleSingleView" fehlt?

**Comment by georgkaser** [comment]
Versteh ich nicht die Frage: Es gibt doch die Funktion printSingleView() - oder was meinst du?

**Comment by ansichtsache** [comment]
tut mir leid, hatte am NewsManager.php rumgefummelt und dadurch $richtext nicht mehr definiert…

**Comment by georgkaser** [comment]
Kein Problem ;) Dann schliesse ich das mal...
