### ISSUE TITLE
Wie gehts denn nun weiter?

### ISSUE THREAD

**Issue by webregie** [FriendsOfREDAXO/newsmanager#31]
Hallo Georg, 

ich habe einen Fork gefunden, wo ein paar Dinge eingebaut sind: https://github.com/ansichtsache/newsmanager. 

Außerdem habe ich im Slack über das Addon diskutiert. Eigentlich sind sich alle einig, dass du die bisher beste Idee/den besten Ansatz hast. Nur mit den Views kommen viele nicht klar. 
Ich würde mich freuen, wenn du sagen kannst, wie es mit dem Addon weitergeht. 

Vielen Dank
Ralf

**Comment by georgkaser** [comment]
Servus Ralf,

ich bin im Moment (also eigentlich schon das ganze Jahr) privat und auch geschäftlich sehr eingespannt und kann erst wieder Zeit in das Addon investieren sobald ich etwas Luft habe. Tut mir leid, dass ich da nichts besseres berichten kann, aber die anderen Dinge gehen im Moment vor (ich würd selber gerne mehr machen - hatte nicht mal Zeit auf den REDAXO Tag zu kommen). 
Aber da das Addon ohnehin bei FriendOfREDAXO liegt, kann jeder gerne dazu beitragen.

Den Fork kenne ich - @ansichtsache hat auch bereits einen Pull Request gemacht (danke dafür!!). Hab mich allerdings noch nicht damit beschäftigen können - hab noch nie einen Pull Request bearbeitet und möchte nichts zerstören - vielleicht kann das jemand machen, der bereits Erfahrung damit hat, ich muss mich da erst schlau machen. Es sollte dann auch eine neue Version in den Installer hochgeladen werden - diese ist schon veraltet.

Zu den Views: Du musst die nicht verwenden. Du kannst alles auch ganz einfach über eine Datenbankabfrage ausgeben, die Views und die vordefinierten Funktionen sind nur ein Feature. Wo hast du denn Probleme mit den Views? Eigentlich sind die recht einfach zu verwenden...

**Comment by webregie** [comment]
Hallo Georg, 

vielen Dank für die ausführliche Antwort. Ich verstehe, dass man dann dies hier nicht als Prio hat. 
Für die Fragen zu den Views muss ich mir auch mal extra Zeit nehmen. 

Hast du evtl. ein Beispiel für die Datenbankanfragen? Vielleicht könnte das noch unter die FAQs vorne und dann ist auch erst einmal alles geklärt und ich werde mich damit weiter beschäftigen. 

Ich freue mich, wenn du dir demnächst auch Zeit nehmen kannst und einen kleinen Anstubs hier geben kannst. 

Gruß und Dank
Ralf

**Comment by georgkaser** [comment]
Ein recht einfaches Beispiel (ungetestet, sollte aber laufen ;)):
```php
$query = 'SELECT * FROM '.rex::getTablePrefix().'newsmanager';

$results = rex_sql::factory()->getArray($query);

if (count($results)) {
    foreach ($results as $result) {
        echo $result['title'];
        echo $result['richtext'];
    }
}

**Comment by schuer** [comment]
Hey @georgkaser,
ich bin nebenbei auf diese Diskussion gestoßen und möchte nur kurz den Gedanken anbringen, ob @ansichtsache vielleicht temporär übernehmen könnte/sollte/möchte, so lange du keine Zeit hast? Alternativ könntest du vielleicht die Arbeit etwas koordinieren, im Sinne von: Was müsste gemacht werden, wo gilt es Fehler zu bereinigen oder Doku zu schreiben, und so weiter. Vielleicht auch Arbeit gezielt delegieren. FOR ist ja ein Gemeinschaftsding, aber ich habe immer das Gefühl, dass ohne konkrete Anliegen und Ansagen sich kaum jemand traut, mit ins Projekt zu springen und womöglich noch federführend dran zu entwickeln.

Aber das nur als Anregung. Soll keinen Stress machen. :)

**Comment by georgkaser** [comment]
Servus @schuer - absolut, fänd ich gut und ich bin da ohnehin ganz uneitel ;) Jeder der Bock hat und was verbessern kann, ist gerne dazu eingeladen das zu tun. Dachte ohnehin das läuft so auf FOR ;)

**Comment by schuer** [comment]
Vielleicht könnt ihr auch Abstimmen, ob @ansichtsache nicht besser selbst die PRs merged, wenn er überzeugt davon ist, dass sie sinnvoll sind und funktionieren, und dass er dann vielleicht auch ein neues Release macht und in den Installer bringt.

Falls dabei Hilfe benötigt wird, gerne immer im Slack melden! Wir tauschen dort auch Zugangsdaten für den Installer aus.

**Comment by schuer** [comment]
> Dachte ohnehin das läuft so auf FOR ;)

Theoretisch ja, praktisch wird oft etwas Kommunikation — manchmal auch Motivation — drumrum benötigt.

**Comment by ansichtsache** [comment]
@schuer 
hallo dirk, gibt es ein einfaches tut (video oder deutscher text?) für die verwendung von github. ich habe bisher wenig (eher keine:) erfahrung damit und etwas sorge, bei einem merge was kaputtzumachen. ansonsten würde ich mich gerne um den merge kümmern – ich finde das addon sehr praktisch…
gruß
tizian

**Comment by schuer** [comment]
Hey @ansichtsache, ich habe auf die Schnelle keinen deutschsprachigen Text gefunden, aber zumindest dieses Video: https://www.youtube.com/watch?v=hSbJaIdqwKg

Beim Mergen kannst du nichts kaputt machen, keine Sorge. Kannst du direkt auf der GitHub-Weboberfläche tun, so wie in dem Video zu sehen (sehr weit am Ende). Vorher siehst du nochmal im Detail, welche Änderungen vorliegen, und dann ist es nur noch der Klick auf »Merge«. (Empfehlung: Benutze den Button »Merge and Rebase«, das macht es in bestimmten Situationen übersichtlicher.)
Damit landet der Code im Repo und der PR wird geschlossen. Mehr ist es gar nicht.

Aber wie gesagt, bei Fragen oder Unsicherheiten gerne immer im Slack nachfragen, dort wird immer gerne geholfen!

**Comment by webregie** [comment]
das ist ja toll, dass an einem Tag hier Bewegung reinkommt. Ich würde das Addon so gerne weiter einsetzen. Das heißt, dass ich jetzt mit dem Fork von @ansichtsache erstmal arbeite. 
Danke für die Reaktionen.

**Comment by Markus-GS** [comment]
Da jetzt wieder Bewegung am Start ist, wird der "Bug" geschlossen.
