### ISSUE TITLE
Subtitle nicht in Installation?

### ISSUE THREAD

**Issue by webregie** [FriendsOfREDAXO/newsmanager#32]
Huhu (ja ich schon wieder)
kann es sein, dass ihr den subtitle nicht in der Installation habt? 

/redaxo/src/addons/newsmanager/lib/NewsManager.php

 $newsArticle->setSubtitle($result->getValue('subtitle'));    
Call to undefined method NewsManagerArticle::setSubtitle()"

**Comment by ansichtsache** [comment]
moin. in welcher datei setzt du denn code den ein?

**Comment by schuer** [comment]
Das neue Release mit den PRs von @ansichtsache muss noch erstellt werden.

**Comment by ansichtsache** [comment]
hi dirk, mergen reicht nicht?

**Comment by schuer** [comment]
Durch das Mergen sind deine Anpassungen im master-Branch gelandet. Würde man den runterladen, hätte man den aktuellen Stand des AddOns. Jedoch verwendet REDAXO ja den Installer zur Distribution von AddOns, deshalb müssen wir ein Release erstellen und dieses im Installer veröffentlichen.

In Kurzform funktioniert das Release so:
1. Als letzte Anpassung in der package.yml die Version erhöhen
2. In Git einen Tag auf diese Version setzen
3. In der GitHub-Weboberfläche ein Release mit diesem neuen Tag erstellen.
4. Das Release als Zip runterladen und in einer REDAXO-Installation aktivieren.
5. Aus dem REDAXO heraus das AddOn im Installer veröffentlichen. Im Namen von FOR. Die Zugangsdaten tauschen wir intern im Slack aus.

**Comment by ansichtsache** [comment]
@schuer 
hi dirk, hilfst du mir da durch? 1. wie setze ich einen TAG auf die aktuelle version und 2. wie erstelle ich den release?
die punkte danach sind klar – zugang klären wir dann wie du sagst im slack.

ach so: das ganze am besten in der weboberfläche von github …

**Comment by schuer** [comment]
@ansichtsache Klar, ich helfe dir gerne. Aber am besten im Slack, oder?

**Comment by Markus-GS** [comment]
Version 1.2.2 ist jetzt im Installer (inklusive der 1.1.0 "Subtitle" G'schichten :))
