### ISSUE TITLE
Kommentarfunktion DSGVO konform

### ISSUE THREAD

**Issue by spiritandsoul** [FriendsOfREDAXO/newsmanager#34]
Hey Leute, ich wollte mal Fragen wie es um den Newsmanager steht? Zumindestens hier auf Github scheint nichts los zu sein.

Seit die DSGVO in Kraft ist habe ich die Kommentarfunktion deaktiviert. Das soll allerdings kein Dauerzustand bleiben. Ich wollte mal Fragen ob es dafür jetzt Lösungen gibt, so dass auch ich den Newsmanager DSGVO konform nutzen könnte? Möchte nicht auf Lösungen wie Disqus zurückgreifen wollen....

Grüße Christian :-)

**Comment by georgkaser** [comment]
Servus ;)

Was meinst du mit DSGVO konform?

**Comment by spiritandsoul** [comment]
Hey, 

ja das Checkbox Gedöns (Mit der Nutzung dieses Formulars erklärst du dich mit der Speicherung und Verarbeitung deiner Daten durch diese Website einverstanden.) 

Eigentlich ist das selbstverständlich, wenn ich kommentiere muss ich Email und Name hinterlassen. 

Der ganz normale DSGVO Wahnsinn!

**Comment by georgkaser** [comment]
Hmm... das hatte ich noch nicht am Schirm. Sollte man einbauen, stimmt.
Aber sonst sollte das schon konform sein, es wird ja keine IP oder dergleichen gespeichert. 

Steht das irgendwo dass man so ein Feld braucht? Dachte das reicht, wenn man das in den Datenschutzerklärungen einfügt...

**Comment by ansichtsache** [comment]
hi,
ich würde einfach den hinweistext mit link auf die datenschutzerklärung unter das kommentarformular klenmmen …

**Comment by spiritandsoul** [comment]
So zu 100 Prozent weiß ich es auch nicht genau. Was ja in letzter Zeit viel Angstmacherei um das Thema. Ich sehe es halt auch auf vielen Webseiten, beim Kontaktformular und bei der Kommentarfunktion. Selbst der Multinewsletter von Tobias hat es.

@ansichtsache  Über den Kommentarbutton damit es klar zu sehen ist. ;-)
