### ISSUE TITLE
Overall Footer

### ISSUE THREAD

**Issue by webregie** [FriendsOfREDAXO/newsmanager#35]
Wie könnte ich mir so etwas auf jeder Seite im Footer anzeigen lassen: 

![2018 08 14_01_sceenshot](https://user-images.githubusercontent.com/3647431/44061214-c173b37c-9f57-11e8-873d-4c63662fa965.jpg)

Vielleicht gibt es einen Code, wo ich direkt an die Datenbank kann? Vielen Dank.

**Comment by ansichtsache** [comment]
hi, du könntest dir den view "article-teaser-list.php" um den termin erweitern.

**Comment by georgkaser** [comment]
Exakt :) - Oder die Daten einfach direkt mittels MySQL auslesen und ausgeben - das geht ja immer:
https://redaxo.org/doku/master/datenbank-queries

**Comment by webregie** [comment]
Danke für die schnelle Antwort. Habt ihr einen Beispielcode für irgendwelche Direktabfragen hier drin? Mir war mal so. Dann kann ich das bauen. Code folgt dann auch.

**Comment by webregie** [comment]
Ganz grob ohne Sprachen geht es so: 
```php
$newsDataId = UrlGenerator::getId();
$newsArticleId = 15;
$sql_limit = "LIMIT 0, 3";

$datas = rex_sql::factory()->getArray('SELECT * FROM rex_newsmanager ORDER BY createdate DESC ' . $sql_limit, [$newsDataId]);
  
if (count($datas)) {
	echo '<ul>';
	foreach ($datas as $data) {
		echo '<li>' . $data['createdate'] . '<a href="' . rex_getUrl($newsArticleId, '', ['newsmanager' => $data['id']]) . '">' . $data['title'] . '</a></li>';
	}
	echo '</ul>';
}
```

**Comment by webregie** [comment]
Mit Datum schick: 
```php
$newsDataId = UrlGenerator::getId();
$newsArticleId = 15;
$sql_limit = "LIMIT 0, 3";

$datas = rex_sql::factory()->getArray("SELECT * FROM rex_newsmanager ORDER BY createdate DESC " . $sql_limit, [$newsDataId]);

if (count($datas)) {
    echo '<ul>';
    foreach ($datas as $data) {
        echo '<li><span class"date">' . date("d.m.Y", strtotime($data['createdate'])) . '</span><br /><a href="' . rex_getUrl($newsArticleId, '', ['newsmanager' => $data['id']]) . '">' . $data['title'] . '</a></li>';
    }
    echo '</ul>';
}
```
