### ISSUE TITLE
Bild nur als Dateiname ausgeben

### ISSUE THREAD

**Issue by georgkaser** [FriendsOfREDAXO/newsmanager#39]
Flexibler wäre eine Ausgabe des Bildes nicht als komplettes Markup sondern lediglich als Dateiname.

**Comment by webregie** [comment]
Sehr gut! Und vielleicht reicht ja ein Bild, was man als Social und Header-Bild nehmen kann. Die Galerie darf optional sein. Aber ich würde das im Editor einbauen, da man ja auch Bilder im Text benötigt.
