### ISSUE TITLE
setlocale(LC_TIME, "de_DE");

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/newsmanager#4]
Für Datumsausgabe deutsch

**Comment by georgkaser** [comment]
Hmmm, das hatte ich eigentlich drin. Muss wieder rausgeflogen sein. Ich kümmer mich drum.

**Comment by claudihey** [comment]
Wird deshalb noch der Umlaut im März nicht richtig angezeigt? Oder hat das andere Gründe?

**Comment by georgkaser** [comment]
Hmm, denke nicht dass es daran liegt. Wenn schon März (glaub Standard wäre March) ausgegeben wird, jedoch der Umlaut falsch dargestellt wird, wird es ein Encoding Problem sein...

**Comment by claudihey** [comment]
Ich habe außerdem das Phänomen, dass in der Listansicht der letzte Umlaut nicht richtig dargestellt wird. Mitten im Text ist alles korrekt und in der Artikelansicht ist auch alles paletti. Hast Du hier eine Idee?
![newsmanager](https://user-images.githubusercontent.com/20659343/34094363-374502be-e3cd-11e7-9d07-092687534598.PNG)

**Comment by georgkaser** [comment]
Hmm, ich versuch das mal zu reproduzieren...

**Comment by georgkaser** [comment]
Hast du im head vom Template `<meta charset="utf-8">` gesetzt?

**Comment by claudihey** [comment]
Jawoll... und in der htaccess steht auch AddDefaultCharset utf-8

**Comment by claudihey** [comment]
Vielleicht noch eine Info... Der Umlaut im Datum wird auch in der Artikelansicht nicht korrekt dargestellt, der Umlaut im Teaser dagegen schon...

**Comment by georgkaser** [comment]
Ich hab ein paar kleine Änderungen durchgeführt (letzte master) - kannst du die mal testen?

**Comment by georgkaser** [comment]
Übrigens: Du kannst beim Teaser selbst bestimmen wo abgeschnitten werden soll. Dazu musst du einfach eine "Horizontale Linie" im Richtext Editor dort setzen, wo der Text abgeschnitten werden soll. Dort wird dann auch abgeschnitten - ansonsten schneidet das Tool bei 300 Zeichen (jetzt auch wortgenau ;)) ab. Ist vielleicht ein bissi komfortabler wenn man das selbst bestimmen kann.
![bildschirmfoto 2017-12-18 um 14 15 09](https://user-images.githubusercontent.com/6472869/34107829-fb249b38-e3fd-11e7-86cb-15af38d0ac48.png)

**Comment by claudihey** [comment]
Hi Georg, hab die master getestet und die Umlaute im Teaser werden jetzt korrekt dargestellt. Der März will aber noch nicht... ;-) Weder in der Artikel- noch in der List-Ansicht.
Das mit der Linie ist super, das hatte ich schon gesehen... muss meine Kundin aber jetzt selbst sehen, was angezeigt werden soll oder nicht... :-)

**Comment by georgkaser** [comment]
Hmm, bei mir geht das überall. Scheint an der Serverkonfiguration zu liegen. Ich hab jetzt bei setlocale mal utf-8 hinzugefügt. Kannst du die letzte Version bitte mal testen, vielleicht klappts jetzt auch bei dir...

**Comment by skerbis** [comment]
Die deutschen Locals sind evtl. nicht installiert. Das kann in der Console per `locale -a` oder per php 
`server('locale -a');`
 überprüft werden

Das Ergebnis sollte dann für Deutsch etwa so aussehen: 

> de_AT
> de_AT.ISO8859-1
> de_AT.ISO8859-15
> de_AT.UTF-8
> de_CH
> de_CH.ISO8859-1
> de_CH.ISO8859-15
> de_CH.UTF-8
> de_DE
> de_DE.ISO8859-1
> de_DE.ISO8859-15
> de_DE.UTF-8

**Comment by georgkaser** [comment]
@claudihey Hats geklappt?

**Comment by claudihey** [comment]
Nein, leider hat's immer noch nicht geklappt. @skerbis , ich habe leider keine Ahnung, wie ich die Locals abfragen kann... in welcher Console??? 
Es wundert mich nur, dass sonst auf der Seite alle Umlaute korrekt dargestellt werden. Da müssten die Zeichensätze doch grundsätzlich da sein...  Vielleicht hilft es, wenn Ihr mal auf die Seite schaut... http://www.kinderbetreuungsboerse.com Im Menüpunkt Blog ein bisschen runterscrollen bis zu den März-Einträgen... Dankeschön!!! Achso... in der DB ist auch utf-8 eingestellt...

**Comment by skerbis** [comment]
Versuch mal ein `utf8_encode ($data )` um den Monat zu setzen den du bekommst. Wenn dann der März richtig geschrieben ist, liefert dein PHP die Locals nicht in UTF-8 aus.

**Comment by claudihey** [comment]
Yeah, das funktioniert! :-) 
Muss ich mich wegen der Locals eigentlich an meinen Provider wenden, oder kann ich das selbst irgendwo einstellen? DomainFactory hatte mir heute nur zurückgemeldet, dass ich über phpMyAdmin utf-8 einstellen soll, aber das war schon korrekt eingestellt... 
Danke Euch beiden!!!

**Comment by georgkaser** [comment]
Wenn du keinen SSH Zugang hast, wirds wahrscheinlich nicht möglich sein für dich das einzustellen. Ich würd beim Provider mit dem Hinweis darauf nochmal fragen, die müssten das schon wissen. Währ schon wichtig dass das korrekt eingestellt ist, sonst hast du überall wo Umlaute mit PHP ausgegeben werden Probleme. Schöne Seite übrigens!
