### ISSUE TITLE
Bessere Fehlerbehandlung bei fehlendem Kommentar-Plugin

### ISSUE THREAD

**Issue by georgkaser** [FriendsOfREDAXO/newsmanager#40]
Wird bei fehlendem Kommentar-Plugin "echo $newsmanager->getCommentJavaScript();" im Template eingegeben, wirft es im Moment noch einen Error. Besser wäre ein Hinweis dass das Kommentar-Plugin fehlt.

**Comment by Markus-GS** [comment]
Mittels Instruktion im README.MD und entsprechendem Code erledigt.

<?php
 if ((rex_plugin::get('newsmanager', 'comments')->isAvailable()) && (get_class($newsmanager) == 'NewsManagerWithComments')) {
   echo $newsmanager->getCommentJavaScript();             
 }
?>
