### ISSUE TITLE
Endung .html

### ISSUE THREAD

**Issue by webregie** [FriendsOfREDAXO/newsmanager#41]
Kann man eigentlich erreichen, dass man die Endung .html für den Blog nutzen kann? Ich habe bei den Einstellungen leider dann blog.html/artikelname.html - was dann natürlich nicht geht...

**Comment by georgkaser** [comment]
Das kannst du erreichen indem du das Addon "yrewrite_scheme" von dem 
fabelhaften @skerbis verwendest.

**Comment by webregie** [comment]
Das ist ja großartig! Vielen Dank (für die Antwort)!
