### ISSUE TITLE
update von ui_tools

### ISSUE THREAD

**Issue by webregie** [FriendsOfREDAXO/newsmanager#42]
Kann es sein, dass durch Umstellung auf rex:ready das Datum nicht mehr richtig übernommen wird? 
Ich bekomme immer den 01.01.1970, 1:00...

**Comment by webregie** [comment]
Im Systemlog bekomme ich auch für den Newsmanager 

Function create_function() is deprecated | redaxo/src/addons/newsmanager/pages/main.php | 167

PHP Version 7.2

**Comment by webregie** [comment]
Vielleicht ist es auch im Zusammenspiel mit yform 3 irgendwie anders? 
https://github.com/yakamara/redaxo_yform/blob/master/lib/yform/value/datestamp.php#L53

**Comment by georgkaser** [comment]
Wie gibst du denn das Datum aus? Und wo genau bekommst du das falsche Datum? Im Backend oder im Frontend?

**Comment by webregie** [comment]
Ich meine das Datum allein beim Speichern des News-Artikels. Wenn ich das Datum eingebe über den Datetimepicker oder mit deaktiviertem Datetimepicker, wird es nicht gespeichert. Das Feld ist leer. In der Übersicht erscheint dann 1.1.1970

**Comment by georgkaser** [comment]
Also - ich hab das mal kurz bei mir lokal getestet: Bei mir funktioniert alles problemlos. Allerdings bin ich misstrauisch geworden, bezüglich deiner Meldung mit ui_tools: Das Newsaddon bringt seinen eigenen Datepicker mit. Wenn du aber den Datepicker von ui_tools installierst, dann verwendet das Addon offensichtlich diesen und der macht Probleme (zumindest bei meiner Installation).
Versuch mal das Plugin "bootstrap-datepicker" von ui_tools zu deaktivieren und teste es dann erneut. Damit sollte es klappen.

**Comment by webregie** [comment]
Das ist krass! Warum komme ich da nicht selbst drauf? Obwohl, ich habe es ja eingekreist vom Problem her. Dann kam bestimmt im letzten Update bei den ui_tools etwas mit, was sich beißt, denn in einer anderen Installation mit älteren ui_tools läuft es. 
Danke für den Schubs! 
Aber vielleicht hilft es ja auch anderen?

**Comment by webregie** [comment]
Ich wollte damit sagen: Mit der Deaktivierung läuft es!

**Comment by georgkaser** [comment]
Klasse, dann kann ich schließen!
