### ISSUE TITLE
Metabeschreibung für Kategorien

### ISSUE THREAD

**Issue by spiritandsoul** [FriendsOfREDAXO/newsmanager#46]
Huhu Georg,

du sag mal ist das vorgesehen, dass die Newsmanager Kategorien Metabeschreibungen bekommen sollen??? Wäre für sauberes SEO wirklich sinnvoll.

LG Christian :-)

PS: Schöne Feiertage! :-D

**Comment by webregie** [comment]
Das habe ich tatsächlich auch schon gefragt.  Gerade in Sachen SEO wäre das mit den Kategorien sinnvoll. 

Vielleicht kann man sich hier mit der Weiterentwicklung beteiligen?

Ich habe den Newsmanager schon in einigen Projekten im Einsatz und doch so die ein oder andere Veränderung eingebaut. 
Oder ist dem Ersteller ein Fork lieber?

**Comment by webregie** [comment]
Meine Frage an @georgkaser war:

Ist eigentlich für den Newsmanager vorgesehen, dass man den Kategorien auch SEO-Beschreibungen vergibt? Wie würdest du sinnvoll vorgehen? Ich habe überlegt im Backend bei den Kategorien 2 Felder anzulegen, die Title und Description enthält. Dann müsste man es ja auch noch ausgeben. Hättest du eine grobe Idee?

Eine grobe Idee als Anstoß würde mir eigentlich ausreichen ;)

**Comment by georgkaser** [comment]
Hallo Leute, sorry, aber ich mach das in der Freizeit und davon hab ich leider im Moment ganz wenig - daher gibt's im Moment keine neuen Features. 
Aber: Ihr habt recht, das sollten wir unbedingt einbauen.
Ich hab das Projekt extra an die Community übergeben, damit jeder, der kann und möchte, daran mitarbeiten kann. Ein Fork ist also nicht notwendig, jeder kann mitwirken (auch @webregie ;)) - 
Oder noch besser: Ihr kommt bei mir vorbei, helft mir meine Baustelle fertigzustellen und dann programmier ich alles was sinnvoll ist ;))

**Comment by AWqxKAWERbXo** [comment]
Falls das irgendwann als Anforderung benötigt wird, darf man mich gerne darauf ansprechen. (Am besten per Mail)
