### ISSUE TITLE
Nicht URL2 kompatibel

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/newsmanager#49]
https://github.com/FriendsOfREDAXO/newsmanager/search?q=UrlGenerator

**Comment by Markus-GS** [comment]
https://github.com/tbaddade/redaxo_url

V2.0.0ß3 derzeit

**Comment by ansichtsache** [comment]
arbeite dran, bekomme aber die einzelansicht noch nicht zum laufen …

**Comment by ansichtsache** [comment]
müsste jetzt eigentlich eine version 1.3.0 mit den von mir vorgeschlagenen änderungen geben – da dann nur noch mit URL 2 lauffähig … ich kapier aber github immer noch nicht …

**Comment by skerbis** [comment]
wenn nur noch url2 kompatibel ist es ein BC-Break und es müsste 2.0 heißen :-)

**Comment by skerbis** [comment]
ich sehe keine Aktualisierung @ansichtsache

**Comment by ansichtsache** [comment]
@skerbis als github-dummy hatte ich einen branch (?)erstellt – den ic h jetzt nicht wiederfinde.
dafür gibt es jetzt unter meinem fork ein 3.0.0alpha release …
[https://github.com/ansichtsache/newsmanager](https://github.com/ansichtsache/newsmanager)

**Comment by skerbis** [comment]
Kann es sein, dass es dieses Branch ist? https://github.com/FriendsOfREDAXO/newsmanager/tree/für-URL-Version-2-1
@ansichtsache

**Comment by skerbis** [comment]
@ansichtsache  hi ...du hast eine 3.0.0 released. Der Stand auf GitHub ist aber ein anderer?

**Comment by ansichtsache** [comment]
ja, richtig. jetzt habe ich das mit den branches glaube ich halbwegs kapiert …

ich habe eine version 3.0.0 released – der master steht aber noch auf 1.2.7 – sollte ich den auch hochziehen – und wenn ja, wie?

danke und gruß
tizian
