### ISSUE TITLE
Id zum News-Artikel gib SEO Fehler

### ISSUE THREAD

**Issue by Achat79** [FriendsOfREDAXO/newsmanager#54]
ID zum Artikel gibt SEO Fehler aus.
SEO sagt, dass die id nicht leer sein darf!

Ich denke in den 2 Dateien die ich unten erwähne, muss ```id=""```   mit einer Variable ergänzt werden!

In der Datei:
article-teaser.php
Zeile 1
```<article id="" class="news-entry news-list-entry grid">```

Und in der Datei:
article-single-view.php
Zeile 7
```<article id="" class="news-entry col-md-12 white">```

**Comment by eaCe** [comment]
@Achat79 die ID wurde mit dem Update im Juli entfernt.
