### ISSUE TITLE
"Call to a member function getName() on null" beim Versuch einen News-Artikel anzulegen

### ISSUE THREAD

**Issue by elektromanager** [FriendsOfREDAXO/newsmanager#55]
Alles wurde frisch installiert:
- REDAXO 5.12.0 installiert
- URL installiert
- Alles aktiviert
- Sobald ich eine News im Newsmanager anlegen will kommt direkt die Fehlermeldung:

**"Call to a member function getName() on null"**

Betroffen ist Zeile 215:
$fragment->setVar('title', $this->i18n('newsmanager_form_article_title') .' ('. rex_clang::get($clang_id)->getName() .')' , false);

Exception Details:
Error thrown with message "Call to a member function getName() on null"

Stacktrace:
#14 Error in /homepages/7/d4295648902/htdocs/9d-consulting.com/redaxo/src/addons/newsmanager/pages/main.php:215
#13 include in /homepages/7/d4295648902/htdocs/9d-consulting.com/redaxo/src/core/lib/packages/package.php:280
#12 rex_package:includeFile in /homepages/7/d4295648902/htdocs/9d-consulting.com/redaxo/src/core/lib/be/controller.php:482
#11 rex_be_controller:{closure} in /homepages/7/d4295648902/htdocs/9d-consulting.com/redaxo/src/core/lib/util/timer.php:57
#10 rex_timer:measure in /homepages/7/d4295648902/htdocs/9d-consulting.com/redaxo/src/core/lib/be/controller.php:483
#9 rex_be_controller:includePath in /homepages/7/d4295648902/htdocs/9d-consulting.com/redaxo/src/core/lib/be/controller.php:432
#8 rex_be_controller:includeCurrentPageSubPath in /homepages/7/d4295648902/htdocs/9d-consulting.com/redaxo/src/addons/newsmanager/pages/index.php:14
#7 include in /homepages/7/d4295648902/htdocs/9d-consulting.com/redaxo/src/core/lib/packages/package.php:280
#6 rex_package:includeFile in /homepages/7/d4295648902/htdocs/9d-consulting.com/redaxo/src/core/lib/be/controller.php:482
#5 rex_be_controller:{closure} in /homepages/7/d4295648902/htdocs/9d-consulting.com/redaxo/src/core/lib/util/timer.php:57
#4 rex_timer:measure in /homepages/7/d4295648902/htdocs/9d-consulting.com/redaxo/src/core/lib/be/controller.php:483
#3 rex_be_controller:includePath in /homepages/7/d4295648902/htdocs/9d-consulting.com/redaxo/src/core/lib/be/controller.php:415
#2 rex_be_controller:includeCurrentPage in /homepages/7/d4295648902/htdocs/9d-consulting.com/redaxo/src/core/backend.php:233
#1 require in /homepages/7/d4295648902/htdocs/9d-consulting.com/redaxo/src/core/boot.php:141
#0 require in /homepages/7/d4295648902/htdocs/9d-consulting.com/redaxo/index.php:9

**Error:** Call to a member function getName() on null
**File:** redaxo/src/addons/newsmanager/pages/main.php
**Line:** 215

<details>
<summary>Stacktrace</summary>

| Function                                     | File                                          | Line     |
| -------------------------------------------- | --------------------------------------------- | -------- |
| include                                      | redaxo/src/core/lib/packages/package.php      | 280      |
| rex_package->includeFile                     | redaxo/src/core/lib/be/controller.php         | 482      |
| rex_be_controller::{closure}                 | redaxo/src/core/lib/util/timer.php            | 57       |
| rex_timer::measure                           | redaxo/src/core/lib/be/controller.php         | 483      |
| rex_be_controller::includePath               | redaxo/src/core/lib/be/controller.php         | 432      |
| rex_be_controller::includeCurrentPageSubPath | redaxo/src/addons/newsmanager/pages/index.php | 14       |
| include                                      | redaxo/src/core/lib/packages/package.php      | 280      |
| rex_package->includeFile                     | redaxo/src/core/lib/be/controller.php         | 482      |
| rex_be_controller::{closure}                 | redaxo/src/core/lib/util/timer.php            | 57       |
| rex_timer::measure                           | redaxo/src/core/lib/be/controller.php         | 483      |
| rex_be_controller::includePath               | redaxo/src/core/lib/be/controller.php         | 415      |
| rex_be_controller::includeCurrentPage        | redaxo/src/core/backend.php                   | 233      |
| require                                      | redaxo/src/core/boot.php                      | 141      |
| require                                      | redaxo/index.php                              | 9        |

</details>
<details>
<summary>System report (REDAXO 5.12.0, PHP 8.0.5, MySQL 5.7.33)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.12.0     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 8.0.5      |
|       OPcache | no         |
|        Xdebug | no         |

| Database      |              |
| ------------: | :----------- |
|       Version | MySQL 5.7.33 |
| Character set | utf8mb4      |

| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | cgi-fcgi   |
|     Webserver | Apache     |

| Request       |                     |
| ------------: | :------------------ |
|       Browser | Chrome/91.0.4472.77 |
|      Protocol | HTTP/1.1            |
|         HTTPS | yes                 |

| Packages                |            |
| ----------------------: | :--------- |
|                  backup | 2.7.0      |
|                be_style | 2.12.0     |
|         be_style/redaxo | 2.12.0     |
|                 install | 2.9.0      |
|           media_manager | 2.11.0     |
|               mediapool | 2.10.0     |
|                metainfo | 2.8.0      |
|             multiupload | 2.1.3      |
|      navigation_factory | 2.0.3      |
|             newsmanager | 1.2.6      |
|               phpmailer | 2.10.1     |
|                 project | dev        |
|               search_it | 6.7.3      |
| search_it/documentation | 6.7.3      |
|               structure | 2.12.0     |
|       structure/content | 2.12.0     |
|                tinymce4 | 1.2.1      |
|                     url | 1.0.1      |
|                   users | 2.8.0      |
|                   xcore | 1.1.4      |
|                   yform | 3.4.1      |
|             yform/email | 3.4.1      |
|           yform/manager | 3.4.1      |
|                yrewrite | 2.7        |

</details>

Ist das ein Bug oder bin ich der Bug? ;)
Wäre für jeden Tipp dankbar!

**Comment by elektromanager** [comment]
Ich habe einen Weg gefunden das Problem zu umgehen und dies könnte ein Indiz für die Lösung sein. Normalerweise wenn man in der Navigation auf den Newsmanager wechselt, dann wird automatisch die erste Sprache ausgewählt. Man sieht das ja rechts über der Newsmanager Tabelle. Bei mir ist es aktuell aber so, das keine Sprache vorausgewählt ist. Dies führt dann beim Versuch einen neuen Beitrag zu erstellen zu dem oben genannten Fehler. Klickt man nun vor dem Anlegen der News vorher auf eine der Sprachen funktioniert alles wie gewohnt.

Warum das alles so ist ist mir schleierhaft.

**Comment by webregie** [comment]
Deswegen habe ich einen Blog in die Struktur integriert. Ich bin weg von dem Newsmanager. Der Vorteil ist auch, dass man interne Verlinkungen besser handhaben kann und die Module, die man für andere Artikel nutzt, ebenso nutzen kann. Es waren mir zu viele Bugs drin.

**Comment by AWqxKAWERbXo** [comment]
@elektromanager handelte es sich im Ursprung um eine REDAXO-4-Installation? Irgendwas scheint mit der clang-id nicht zu stimmen. Evtl. ein Problem mit System > Sprache.
