### ISSUE TITLE
SQL Fehler: Column already exists: 1060 Duplicate column name 'id'

### ISSUE THREAD

**Issue by godsdog** [FriendsOfREDAXO/newsmanager#56]
Moin, wenn ich die aktuelle Version installiere und die Addon Seite aufrufe, knallt es mit:

`Error while executing statement "SELECT COUNT(*) AS rows FROM (SELECT pid, id, id, title,createdate,status,clang_id FROM rex_newsmanager WHERE clang_id = 1 ORDER BY createdate DESC) t": SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'id'`

In der /pages/main.php muss es in Zeile 159 so lauten:
`$list = rex_list::factory('SELECT pid, id, title,createdate,status,clang_id FROM ' . rex::getTablePrefix() . 'newsmanager WHERE clang_id = '.$clang_id.' ORDER BY createdate DESC', 25);`
statt:
`$list = rex_list::factory('SELECT pid, id, id, title,createdate,status,clang_id FROM ' . rex::getTablePrefix() . 'newsmanager WHERE clang_id = '.$clang_id.' ORDER BY createdate DESC', 25);`

`id` ist doppelt.

PULL Request: https://github.com/FriendsOfREDAXO/newsmanager/pull/57

**Comment by Markus-GS** [comment]
Fixed by godsdog and ansichtsache 10 Dec 21.
