### ISSUE TITLE
SQL errors / Nutzung unmöglich

### ISSUE THREAD

**Issue by elektromanager** [FriendsOfREDAXO/newsmanager#58]
REDAXO | 5.14.1
PHP | 8.0.23

Also mir ist es unmöglich den Newsmanager ans laufen zu bekommen.

Ich lade URL von Thomas Blum in der Version 2.0.2 über den REDAXO Installer herunter und lasse es installieren. Funktioniert.
Ich lade Newsmanager 3.0.1 (Aktuelles Release) über den REDAXO Installer herunter und lasse es installieren. Funktioniert.

Ich klicke im Seitenmenu von REDAXO auf News Manager und dann auf Einstellungen um den Artikel für die Newsansicht auszuwählen.  Ich wähle im Dropdown den Artikel aus und sobald ich auf speichern klicke:

`Error while executing statement "DELETE FROM `rex_url_generate` WHERE `table` = '1_xxx_rex_newsmanager'" using params []! SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dbs8735023.rex_url_generate' doesn't exist`

Ich checke per phpMyAdmin die Datenbank: Es gibt keine Tabelle mit der Bezeichnung "rex_url_generate" . Es gibt aber "rex_url_generator_profile" und "rex_url_generator_url". 

Ich klicke erneut auf Einstellungen und der Artikel für die Newsansicht ist trotzdem gesetzt.

Also versuche ich mal eine News anzulegen und wechsle auf "News Anlegen".
Dort ist immer noch der Bug das die Sprache nicht vorausgewählt ist, was dazu führt das wenn man nicht manuell auf die Sprache klickt wieder ein Fehler ausgeworfen wird:
`Call to a member function getName() on null`

Das war mir dann alles zu heikel und ich wollte das Addon wieder entfernen.

Beim Versuch das AddOn wieder zu deinstallieren kommt folgende Meldung vom REDAXO:
```
AddOn newsmanager konnte aus folgendem Grund nicht deinstalliert werden:
SQL error: Error while executing statement "DELETE FROM `rex_url_generate` WHERE `table` = 'rex_1_xxx_rex_newsmanager';" using params []! SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dbs8735023.rex_url_generate' doesn't exist
```

Bleibt nur per FTP den Ordner zu entfernen.

Ich habe dieses Addon immer gerne eingesetzt und es gibt auch keine praktische Alternative im Angebot, deshalb meine Frage: Was ist da los? Seit REDAXO 5 fliegt mir das immer wieder um die Ohren und die letzten Updates haben es unmöglich gemacht es einzusetzen. Liegt der Fehler bei mir, übersehe ich etwas? Wäre für eine Antwort dankbar.

**Comment by georgkaser** [comment]
Servus. Ich hab das Ding zwar mal vor Jahren programmiert, aber mittlerweile setze ich das gar nicht mehr ein und deshalb pflegen das Addon andere Leute. 

Ich hab mirs jetzt mal installiert und versucht einzurichten - soweit ich sehen kann, ist es nicht mit dem neuen url Addon kompatibel - müsste man umschreiben (das dir da REDAXO um die Ohren fliegt, liegt nicht an REDAXO - das ist nämlich stabil - sondern am Addon :))

Ich persönlich verwende in der Zwischenzeit für Newszwecke tatsächlich einfach REDAXO Kategorien und Artikel oder für eine einfache Newsfunktion den Table Manager von yform.

Man sollte das Addon aus dem Installer rausnehmen wenn es nicht funktioniert - leider weiß ich nicht wie das geht, vielleicht kann das jemand übernehmen?

**Comment by AWqxKAWERbXo** [comment]
@georgkaser @ansichtsache ihr steht beide als Projekt-Lead drin, klärt das doch entsprechend ab und nehmt euch raus, wenn ihr das Addon nicht mehr begleitet.

**Comment by georgkaser** [comment]
Erledigt :)

**Comment by eaCe** [comment]
Ich habe ein paar fixes gepushed. Uninstall sollte gehen, ebenso das hinzufügen von Artikeln und Kategorien. Die Tabellen haben sich etwas verändert. Ich habe noch ein paar Probleme mit dem URL2-Definitionen. Kann mir jemand sagen wie die URLs mal ausgesehen haben? Wurde nur der Titel genutzt oder auch die ID?

**Comment by eaCe** [comment]
Es ist nur der Titel, wenn ich es richtig sehe

**Comment by eaCe** [comment]
@elektromanager möchtest du mal die aktuelle Github-Version testen. Bitte vorher sicherheitshalber ein Backup machen...

**Comment by skerbis** [comment]
@ansichtsache ich stelle nun ein Release bereit.
