### ISSUE TITLE
Zusammenspiel mit URL-Addon

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/newsmanager#6]
Macht bei uns Probleme. Mal geht es mal nicht. 
Meist bekomme ich immer URLs mit newsmanager=1
Die News kann dann nicht aufgerufen werden.

**Comment by georgkaser** [comment]
Scheint was mit den Sprachen zu tun zu haben. Hast du nur eine oder mehrere Sprachen aktiviert?

**Comment by georgkaser** [comment]
Ich habs grad nochmal mit einer ganz frischen Installation getestet. Bei mir funktioniert das problemlos. Hast du in den Einstellungen denn auch die richtige Kategorie ausgewählt? Wurden die Einträge im URL Addon korrekt angelegt?

**Comment by skerbis** [comment]
Unsere Testseite ist 2 sprachig - Ein Cache löschen hilft nicht

**Comment by tbaddade** [comment]
> Unsere Testseite ist 2 sprachig

@skerbis Url Profil richtig angelegt?

**Comment by georgkaser** [comment]
Wir habens grad rausgefunden: "Startsprache nicht in URL" war nicht aktiviert im yrewrite Addon. Scheinbar schreibt da das url Addon noch was anderes in die Datenbank... Ich versuch das rauszufinden!

**Comment by skerbis** [comment]
@tbaddade ja ist korrekt. Es scheint ein Mehrsprachproblem zu sein. @georgkaser ist informiert

**Comment by georgkaser** [comment]
Vorerst einfach "Startsprache nicht in URL" im yrewrite Addon aktivieren, dann funktionierts...

**Comment by georgkaser** [comment]
@tbaddade Du kennst dich ja am besten mit dem url Addon aus: Ich kann den Fehler nicht reproduzieren, bei mir funktionierts das mit Startsprache und ohne. Kann es sein, dass das ein Caching Problem ist?

**Comment by skerbis** [comment]
Ich habe die Vermutung es klappt nur, wenn in YRewrite die Domain auch hinterlegt wurde

**Comment by tbaddade** [comment]
Wie editiere ich die News in anderen Sprachen? In die DB werden diese korrekt gespeichert.

**Comment by skerbis** [comment]
@tbaddade Sprache auswählen und editieren?

**Comment by georgkaser** [comment]
@skerbis ja, geht das denn ohne eine Domain anzulegen? Ich leg immer eine Domain an, wenn ich yrewrite benutze...

**Comment by georgkaser** [comment]
@tbaddade Genau, ich hab einen Sprachwechsler in der Listenansicht angelegt. Die unterschiedlichen Einträge werden dann mit der jeweiligen Sprach-ID in die Datenbank geschrieben (hab ich mir von REDAXO selbst abgeschaut ;)). Daran kann es meiner Meinung nach nicht liegen...

**Comment by skerbis** [comment]
yrewrite geht auch ohne Angabe der Domain (wenn es nur eine ist) , ich glaube aber tatsächlich das URL-AddOn ohne Domain nicht klarkommt

**Comment by georgkaser** [comment]
Ah, okay. Das hab ich noch nicht getestet. Kann ich das irgendwie abfangen?

**Comment by tbaddade** [comment]
> Sprache auswählen und editieren?

Wo? 
![screenshot 2017-10-20 17 32 46](https://user-images.githubusercontent.com/338267/31829162-c7ee616e-b5bc-11e7-9a97-048e54e673c4.png)

**Comment by georgkaser** [comment]
Hast du eine weitere Sprache angelegt und aktiviert? Da müsste rechts ein Sprachwechsler kommen.

**Comment by skerbis** [comment]
![bildschirmfoto 2017-10-20 um 17 34 49](https://user-images.githubusercontent.com/791247/31829240-ff9ad994-b5bc-11e7-940b-b152eff0923d.png)

**Comment by skerbis** [comment]
Es ist verhext. Ich habe die Domain jetzt wieder aus rausgenommen, dennoch funktioniert es. grummel... cache übrigens gelöscht ... sehr merkwürdig

**Comment by georgkaser** [comment]
Wenn du dann in den Einstellungen nochmal speicherst, wird der url-Addon Cache gelöscht. Versuch das mal... (via `UrlGenerator::generatePathFile([]);`)

**Comment by skerbis** [comment]
hmm ... jetzt alles gut

**Comment by georgkaser** [comment]
Wars das Caching?

**Comment by skerbis** [comment]
Stop. Ich habe jetzt einfach mal den Artikel gewechselt und dann wieder zurückgestellt... jetzt ist der Effekt wieder da

**Comment by tbaddade** [comment]
> Hast du eine weitere Sprache angelegt und aktiviert? Da müsste rechts ein Sprachwechsler kommen.

Alles dabei. Fehlt nur der Sprachwechsler.
@skerbis Am besten kopiere dir mal die pathlist in ein Json Visualizer (ich nutze den hier[1]). Dann kann man das Array mal durchgehen und die generierten Urls sehen. Bei mir sehen die Urls in der Pathlist alle korrekt, egal ob Domain in yrewrite vorhanden ist oder nicht.

[1] http://youknowone.github.io/VisualJSON/

**Comment by skerbis** [comment]
Wenn ich in URL gehe und dann die Einstellungen dort noch mal speichere ... geht es wieder

**Comment by tbaddade** [comment]
> Ich habe jetzt einfach mal den Artikel gewechselt und dann wieder zurückgestellt

Dann wird die pathlist vermutlich nicht neu generiert.

**Comment by georgkaser** [comment]
https://github.com/FriendsOfREDAXO/newsmanager/blob/ce84472c7cede943eeb717765bc58081d0fa1b41/pages/settings.php#L53 müsste eigentlich reichen, nicht?

**Comment by skerbis** [comment]
Erst wenn ich den Cache anschließend lösche, geht es wieder. Kann es sein, dass yrewrite es nicht mitbekommt?

**Comment by georgkaser** [comment]
Führe `UrlGenerator::generatePathFile([]);` jetzt auch beim speichern, updaten und ändern des Status aus. Die URLs sollten jetzt jedenfalls korrekt generiert werden. Ansonsten einfach nochmal melden.
