### ISSUE TITLE
Update auf den neuen Redactor text editor 

### ISSUE THREAD

**Issue by my-steffen** [FriendsOfREDAXO/newsmanager#62]
**Feature description / Feature Beschreibung**
Aktuell ist noch der Redactor2 aktiv, wäre cool wenn es auf den Redactor3 gefixt wird.

**Comment by AWqxKAWERbXo** [comment]
Wenn du hier nicht weiter kommst, im Addon `neues` https://github.com/alexplusde/neues kann man den Editor selbst einstellen.

**Comment by eaCe** [comment]
Redactor wird nicht weiter entwickelt da die Lizenz zu teuer ist. Ich denke es ergibt Sinn CKE oder Tiny zu verwenden. Diese könnte man optional einstellen.

**Comment by AWqxKAWERbXo** [comment]
> Redactor wird nicht weiter entwickelt da die Lizenz zu teuer ist.

Woher stammt diese Information?

**Comment by eaCe** [comment]
Ok, genauer:
> der Redactor wird nicht weiter entwickelt bzw. für den Nachfolger wollen Sie wieder eine Lizenzgebühr

Das hatte Thomas mir mitgeteilt, daher setzen sie vermehrt auf Tiny

**Comment by AWqxKAWERbXo** [comment]
Es findet sich aktuell niemand, der das umsetzt und es gibt gute Alternativen, wie wir gerade auf Jitsi erörtert haben. Von der eigenen kleinen Tabelle in YForm über Artikel + Meta Infos bis hin zur größeren Lösung [von mir.](https://github.com/alexplusde/neues).
