### ISSUE TITLE
Reihenfolge der Abfrage

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/newsmanager#7]
Ich schlage vor: 
- Titel
- Subtitel (Wunsch) 
- Datum 
- (Uhrzeit getrennt, wäre toll) 
- Kategorie
- News
…

**Comment by georgkaser** [comment]
Was meinst du mit Reihenfolge? Die Reihenfolge bei der Ausgabe? Die kann man in den Views anpassen (Siehe README - letzter Absatz. Sollte ich vielleicht noch ein wenig hervorheben).

Mit Subtitel - meinst du damit den Kurztext für den Teaser z.B.? Das geht schon, ich hab das ein wenig eigen gelöst: Man kann im Richtext einfach eine horizontale Linie (`<hr>`) einfügen. Damit kann man den Text teilen (so wie in Wordpress).

**Comment by skerbis** [comment]
1. Reihenfolge in der Einpflege
2. Subtitel = 2. Überschrift... z.B. 

**1:0 für FV Butterweich**
*Die Verlierer von gestern*

...
Teasertext für die Anreißer auch gut

**Comment by georgkaser** [comment]
Hmm, ich weiß nicht. Einen Subtitel wollte ich eigentlich nicht einbauen - ich wollte es möglichst einfach halten. Reicht es nicht, wenn man das im Richtext einfach dann eingibt und über den Anreißer ausgibt?

Zur Reihenfolge: Bin ich auch noch nicht ganz sicher, ob ich da was ändern möchte. Das ist ja eigentlich im großen und ganzen eh so wie von dir gefordert? Warum möchtest du die Uhrzeit extra haben? Die kann man doch ganz komfortabel mit dem Kalender auswählen.

**Comment by skerbis** [comment]
Der Datepicker ist nicht sehr intuitiv. Eine Trennung von Datum und Uhrzeit (vielleicht auch nur optisch) würde es vereinfachen. Auch eine deutsche Schreibweise der Angaben wäre gut.

**Comment by skerbis** [comment]
Beispiel: Sked - Trennung Uhrzeit / Datum
![bildschirmfoto 2017-10-20 um 17 26 14](https://user-images.githubusercontent.com/791247/31828864-d80e6cd4-b5bb-11e7-85e2-d2f03056e541.png)

**Comment by georgkaser** [comment]
Habe Datum und Uhrzeit jetzt getrennt:

<img width="648" alt="bildschirmfoto 2017-11-29 um 22 30 53" src="https://user-images.githubusercontent.com/6472869/33400101-2a1be21e-d555-11e7-998b-5a112f32a913.png">
