### ISSUE TITLE
Editor-Auswahl

### ISSUE THREAD

**Issue by javanita** [FriendsOfREDAXO/newsmanager#9]
Ich fände es toll, wenn man den Editor auswählen könnte. Vielleicht in einer späteren Version.

Ansonsten muss ich sagen: sehr gute Arbeit.

**Comment by georgkaser** [comment]
Danke ;) Ja, daran hatte ich auch schon gedacht. Bin nicht recht zufrieden mit dem redactor. Eine Idee wäre, zu überprüfen, welche Editoren installiert sind und über ein Dropdown eine Möglichkeit zu bieten, einen Editor auszuwählen. Damit muss ich mich aber mit den anderen erst beschäftigen.

**Comment by webregie** [comment]
Ich schließe mich hier an. Der TiyMCE wäre gut, Immerhin ist er ja jetzt in der neuen Version dabei. 
Tolles Addon mit Potential!

**Comment by georgkaser** [comment]
Ja, da bin ich schon dran, der TinyMCE funktioniert auch für mich besser. Es wird eine Auswahlmöglichkeit geben.

**Comment by webregie** [comment]
Ich wäre begeistert!

**Comment by webregie** [comment]
Ich traue mich gar nicht zu fragen wie weit du damit bist. Ich würde sonst selbst mal ran...

**Comment by georgkaser** [comment]
Bitte gerne - ich komm im Moment nicht dazu!

**Comment by webregie** [comment]
Ja, ich will da nicht eingreifen in deine Ideen. Habe in Z134 der /pages/main.php nun die Editor-Klasse gegen "tinyMCEEditor"  ausgetauscht. Da wohl auch der CKE über eine Klasse gesteuert wird, könnte man in den Einstellungen vielleicht eine Auswahl haben.

**Comment by georgkaser** [comment]
Ja, wie gesagt, ich hab vor das einzubauen. Denke es soll ein Dropdown sein, welches die installierten Editoren auflistet und man da auswählen kann. Du kannst die Klasse natürlich gerne in deiner Version abändern um den Editor deiner Wahl jetzt schon zu benutzen.
